//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskrForms.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskrForms.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string AddTaskButton {
            get {
                return ResourceManager.GetString("AddTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskr.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string AppWelcomeButton {
            get {
                return ResourceManager.GetString("AppWelcomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Taskr!.
        /// </summary>
        internal static string AppWelcomeMessage {
            get {
                return ResourceManager.GetString("AppWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionTitle {
            get {
                return ResourceManager.GetString("DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        internal static string MyTasksTitle {
            get {
                return ResourceManager.GetString("MyTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description of your task.
        /// </summary>
        internal static string NoTaskDescriptionMessage {
            get {
                return ResourceManager.GetString("NoTaskDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutTitle {
            get {
                return ResourceManager.GetString("SignOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a Task.
        /// </summary>
        internal static string SubmitATaskTitle {
            get {
                return ResourceManager.GetString("SubmitATaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task description.
        /// </summary>
        internal static string TaskEditorPlaceholder {
            get {
                return ResourceManager.GetString("TaskEditorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed By.
        /// </summary>
        internal static string TaskrAboutFooter {
            get {
                return ResourceManager.GetString("TaskrAboutFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  here .
        /// </summary>
        internal static string TaskrAboutLinkHere {
            get {
                return ResourceManager.GetString("TaskrAboutLinkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Intune .
        /// </summary>
        internal static string TaskrAboutLinkIntune {
            get {
                return ResourceManager.GetString("TaskrAboutLinkIntune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Microsoft.
        /// </summary>
        internal static string TaskrAboutLinkMicrosoft {
            get {
                return ResourceManager.GetString("TaskrAboutLinkMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskr is a line-of-business app that allows employees to keep a personal to-do list. It is a demonstration of Microsoft&apos;s Xamarin MAM SDK, an.
        /// </summary>
        internal static string TaskrAboutSection1 {
            get {
                return ResourceManager.GetString("TaskrAboutSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product..
        /// </summary>
        internal static string TaskrAboutSection2 {
            get {
                return ResourceManager.GetString("TaskrAboutSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information about the SDK is available.
        /// </summary>
        internal static string TaskrAboutSection3 {
            get {
                return ResourceManager.GetString("TaskrAboutSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and a developer guide is available.
        /// </summary>
        internal static string TaskrAboutSection4 {
            get {
                return ResourceManager.GetString("TaskrAboutSection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string TaskrAboutSection5 {
            get {
                return ResourceManager.GetString("TaskrAboutSection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ToolbarItemCancel {
            get {
                return ResourceManager.GetString("ToolbarItemCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string ToolbarItemComplete {
            get {
                return ResourceManager.GetString("ToolbarItemComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string ToolbarItemPrint {
            get {
                return ResourceManager.GetString("ToolbarItemPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ToolbarItemSave {
            get {
                return ResourceManager.GetString("ToolbarItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tasks.
        /// </summary>
        internal static string ToolbarItemSaveTasks {
            get {
                return ResourceManager.GetString("ToolbarItemSaveTasks", resourceCulture);
            }
        }
    }
}
